CREATE TABLE "categories" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR NOT NULL
);

INSERT INTO "categories" ("id", "name") VALUES
(000, 'Computer Science, Information & General Works'),
(100, 'Philosophy & Psychology'),
(200, 'Religion'),
(300, 'Social Sciences'),
(400, 'Language'),
(500, 'Science'),
(600, 'Technology'),
(700, 'Arts & Recreation'),
(800, 'Literature & Poetry'),
(900, 'History & Geography');

-- SELECT * FROM "categories";

CREATE TABLE "books" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

    "isbn" CHAR(17) NOT NULL,
    "name" VARCHAR NOT NULL,
    "author" VARCHAR NOT NULL,

    "id_category" INTEGER REFERENCES "categories" ("id")
);

INSERT INTO "books" ("isbn", "name", "author", "id_category")
WITH "new_books" ("isbn", "name", "author", "category") AS (
    VALUES
    ('978-0-13-235088-4', 'Clean Code', 'Robert C. Martin', 'Computer Science, Information & General Works'),
    ('978-0-374-53355-7', 'Thinking, Fast and Slow', 'Daniel Kahneman', 'Philosophy & Psychology'),
    ('978-0-06-065292-0', 'Mere Christianity', 'C. S. Lewis', 'Religion'),
    ('978-0-06-231609-7', 'Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'Social Sciences'),
    ('978-0-205-30902-3', 'The Elements of Style', 'William Strunk Jr. & E. B. White', 'Language'),
    ('978-0-553-38016-3', 'A Brief History of Time', 'Stephen Hawking', 'Science'),
    ('978-0-465-05065-9', 'The Design of Everyday Things', 'Don Norman', 'Technology'),
    ('978-0-7148-3247-0', 'The Story of Art', 'E. H. Gombrich', 'Arts & Recreation'),
    ('978-0-14-143951-8', 'Pride and Prejudice', 'Jane Austen', 'Literature & Poetry'),
    ('978-0-393-35432-4', 'Guns, Germs, and Steel', 'Jared Diamond', 'History & Geography')
)
SELECT "b"."isbn", "b"."name", "b"."author", "c"."id" FROM "new_books" "b"
JOIN "categories" "c" ON "c"."name" = "b"."category";

-- SELECT * FROM "books";

CREATE TABLE "bookcases" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

    "floor" INTEGER NOT NULL,
    "aisle" INTEGER NOT NULL
);

INSERT INTO "bookcases" ("floor", "aisle") VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(2, 1),
(2, 2),
(2, 3),
(2, 4),
(2, 5),
(2, 6);

-- SELECT * FROM "bookcases";

CREATE TABLE "bookcases_categories" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

    "id_category" INTEGER REFERENCES "categories" ("id"),
    "id_bookcase" INTEGER REFERENCES "bookcases" ("id")
);

INSERT INTO "bookcases_categories" ("id_category", "id_bookcase")
WITH "new_bookcases_categories" ("floor", "aisle", "category") AS (
    VALUES
    (1, 1, 'Computer Science, Information & General Works'),
    (1, 2, 'Philosophy & Psychology'),
    (1, 3, 'Religion'),
    (1, 4, 'Social Sciences'),
    (2, 1, 'Language'),
    (2, 2, 'Science'),
    (2, 3, 'Technology'),
    (2, 4, 'Arts & Recreation'),
    (2, 5, 'Literature & Poetry'),
    (2, 6, 'History & Geography')
)
SELECT "c"."id", "b"."id" FROM "new_bookcases_categories" "n"
JOIN "categories" "c" ON "c"."name" = "n"."category"
JOIN "bookcases" "b" ON "b"."floor" = "n"."floor" AND "b"."aisle" = "n"."aisle";

-- SELECT * FROM "bookcases_categories";

CREATE TABLE "people" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

    "name" VARCHAR NOT NULL,
    "phone" VARCHAR NOT NULL,
    "address" VARCHAR NOT NULL,
    "gender" VARCHAR,
    "birthdate" DATE
);

INSERT INTO "people" ("name", "phone", "address", "gender", "birthdate") VALUES
('Adinda Puspitasari', '+62 812-3345-9021', 'Jl. Cihampelas No. 142, Bandung, Jawa Barat 40131', 'female', '1996-04-17'),
('Bagus Nurwanto', '+62 857-2210-7788', 'Jl. Kaliurang KM 5 No. 8, Sleman, DI Yogyakarta 55281', 'male', '1989-11-02'),
('Citra Halimah Wijaya', '+62 813-9087-1145', 'Perumahan Griya Asri Blok C2/14, Bekasi, Jawa Barat 17114', 'female', '2001-06-28'),
('Damar Setiawan', '+62 878-4412-6630', 'Jl. Diponegoro No. 77, Surabaya, Jawa Timur 60241', 'male', '1993-01-09'),
('Elina Rahmadani', '+62 895-3320-4417', 'Jl. Gajah Mada No. 26, Denpasar, Bali 80119', 'female', '1998-09-14'),
('Fajar Ramadhan Putra', '+62 821-6654-8809', 'Jl. Ahmad Yani No. 301, Medan, Sumatera Utara 20111', 'male', '1985-03-22'),
('Gita Larasati', '+62 856-1178-2263', 'Jl. Pemuda No. 45, Semarang, Jawa Tengah 50132', 'female', '2003-12-05'),
('Hendra Kusuma', '+62 838-7729-5504', 'Jl. Sam Ratulangi No. 19, Makassar, Sulawesi Selatan 90114', 'male', '1991-07-30'),
('Intan Maharani', '+62 811-4490-3376', 'Jl. Sudirman No. 8, Palembang, Sumatera Selatan 30129', NULL, '1999-02-11'),
('Joko Prasetyo', '+62 852-6603-1198', 'Jl. Cendrawasih No. 63, Balikpapan, Kalimantan Timur 76112', 'male', NULL);

-- SELECT * FROM "people";

CREATE TABLE "patrons" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

    "id_person" INTEGER UNIQUE REFERENCES "people"("id")
);

CREATE TABLE "bookkeepers" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

    "id_person" INTEGER UNIQUE REFERENCES "people"("id")
);

INSERT INTO "patrons" ("id_person")
WITH "new_patrons" ("name") AS (
    VALUES
    ('Adinda Puspitasari'),
    ('Bagus Nurwanto'),
    ('Citra Halimah Wijaya'),
    ('Damar Setiawan'),
    ('Elina Rahmadani'),
    ('Fajar Ramadhan Putra')
)
SELECT "p"."id" FROM "new_patrons" "n"
JOIN "people" "p" ON "p"."name" = "n"."name";

INSERT INTO "bookkeepers" ("id_person")
WITH "new_bookkeepers" ("name") AS (
    VALUES
    ('Gita Larasati'),
    ('Hendra Kusuma'),
    ('Intan Maharani'),
    ('Joko Prasetyo')
)
SELECT "p"."id" FROM "new_bookkeepers" "n"
JOIN "people" "p" ON "p"."name" = "n"."name";

-- SELECT "p"."name", 'patron' AS "role" FROM "patrons" "pt"
-- JOIN "people" "p" ON "p"."id" = "pt"."id_person"
-- UNION ALL
-- SELECT "p"."name", 'bookkeeper' AS "role" FROM "bookkeepers" "bk"
-- JOIN "people" "p" ON "p"."id" = "bk"."id_person"
-- ORDER BY "role", "name";

CREATE TABLE "shifts" (
    "id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

    "id_bookkeper" INTEGER REFERENCES "bookkeepers"("id"),

    "shift_date" DATE NOT NULL,
    "start_time" TIME NOT NULL,
    "end_time" TIME NOT NULL
);

INSERT INTO "shifts" ("id_bookkeper", "shift_date", "start_time", "end_time")
WITH "new_shifts" ("name", "shift_date", "start_time", "end_time") AS (
    VALUES
('Gita Larasati',  DATE '2026-07-06', TIME '08:00', TIME '14:00'),
('Hendra Kusuma',  DATE '2026-07-06', TIME '14:00', TIME '20:00'),
('Intan Maharani', DATE '2026-07-07', TIME '08:00', TIME '14:00'),
('Joko Prasetyo',  DATE '2026-07-07', TIME '14:00', TIME '20:00'),
('Gita Larasati',  DATE '2026-07-08', TIME '08:00', TIME '14:00'),
('Hendra Kusuma',  DATE '2026-07-08', TIME '14:00', TIME '20:00'),
('Intan Maharani', DATE '2026-07-09', TIME '08:00', TIME '14:00'),
('Joko Prasetyo',  DATE '2026-07-09', TIME '14:00', TIME '20:00'),
('Gita Larasati',  DATE '2026-07-10', TIME '08:00', TIME '14:00'),
('Hendra Kusuma',  DATE '2026-07-10', TIME '14:00', TIME '20:00'),
('Intan Maharani', DATE '2026-07-11', TIME '08:00', TIME '14:00'),
('Joko Prasetyo',  DATE '2026-07-11', TIME '14:00', TIME '20:00'),
('Gita Larasati',  DATE '2026-07-12', TIME '10:00', TIME '16:00'),
('Hendra Kusuma',  DATE '2026-07-12', TIME '16:00', TIME '20:00')
)
SELECT "b"."id", "n"."shift_date", "n"."start_time", "n"."end_time"
FROM "new_shifts" "n"
JOIN "people" "p" ON "p"."name" = "n"."name"
JOIN "bookkeepers" "b" ON "b"."id_person" = "p"."id";

-- SELECT * FROM "shifts";
