CREATE TABLE "categories" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR NOT NULL
);

INSERT INTO "categories" ("id", "name") VALUES
(000, 'Computer Science, Information & General Works'),
(100, 'Philosophy & Psychology'),
(200, 'Religion'),
(300, 'Social Sciences'),
(400, 'Language'),
(500, 'Science'),
(600, 'Technology'),
(700, 'Arts & Recreation'),
(800, 'Literature & Poetry'),
(900, 'History & Geography');

-- SELECT * FROM "categories";
